# Generated by Django 5.1.2 on 2024-10-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
