# Generated by Django 5.1.2 on 2024-10-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_test_alter_buyer_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
